# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby, :x64_mingw]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw, :x64_mingw]
# # If you do not have OpenSSL installed, change
# # the following line to use 'http://'
# source 'https://rubygems.org'

# # For faster file watcher updates on Windows:
# gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# # Windows does not come with time zone data
# gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

gem 'haml'

# Middleman Gems
# gem 'middleman', '>= 4.0.0'
gem 'middleman-livereload'
gem 'middleman-compass', '>= 4.0.0'
gem 'middleman-sprockets'
gem 'middleman-minify-html'
gem 'middleman-robots'
# gem 'builder'
# gem 'middleman-search_engine_sitemap'
gem 'middleman-sitemap'
# gem 'middleman-pagegroups'
# gem 'middleman-meta-tags'
# gem 'middleman-google-analytics'
gem 'bootstrap-sass'
gem 'redcarpet'

gem 'middleman-google-analytics', '~> 3.0'
gem 'middleman-search_engine_sitemap'

gem "middleman-blog", "~> 4.0"
gem 'middleman-cli'
gem 'nokogiri'
gem 'middleman-deploy', github: 'middleman-contrib/middleman-deploy', branch: 'master'
gem "middleman-imageoptim", :git => "https://github.com/plasticine/middleman-imageoptim", :branch => "master"

# gem 'middleman-gibberish', :git => 'https://github.com/ahoward/middleman-gibberish.git'
# gem 'middleman-gibberish', :git => 'https://github.com/marwann/gibberish-custom.git'

